-- 코드를 입력하세요
SELECT PRODUCT_CODE as PRODUCT_CODE, sum(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) as SALES
from PRODUCT, OFFLINE_SALE
where PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
group by PRODUCT.PRODUCT_CODE
order by SALES DESC, PRODUCT_CODE ASC