-- 코드를 입력하세요
SELECT  
USED_GOODS_BOARD.TITLE, 
USED_GOODS_BOARD.BOARD_ID, 
USED_GOODS_REPLY.REPLY_ID, 
USED_GOODS_REPLY.WRITER_ID, 
USED_GOODS_REPLY.CONTENTS, 
date_format(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD, USED_GOODS_REPLY
where 
YEAR(USED_GOODS_BOARD.CREATED_DATE) = 2022 and MONTH(USED_GOODS_BOARD.CREATED_DATE) = 10 and 
USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
order by CREATED_DATE, USED_GOODS_BOARD.TITLE asc